CREATE TABLE yanshi2
(
    id INT NOT NULL AUTO_INCREMENT COMMENT 'string',
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE=INNODB CHARACTER SET=utf8 COMMENT='≤‚ ‘'