on: [pull_request]
jobs:
  bytebase-sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - name: SQL advise
        run: |
          API="http://30.20.169.95:5678/hook/sql-review/4c5b2aa7-378a-4aca-b260-8351afb7e26a-1686216013"
          TOKEN="${{ secrets.SQL_REVIEW_API_SECRET }}"
          echo "Start request $API"

          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          repository=`echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'`
          request_body=$(jq -n \
            --arg repositoryId "$repository" \
            --arg pullRequestId $pull_number \
            --arg webURL "$GITHUB_SERVER_URL" \
            '$ARGS.named')

          response=$(curl -s -w "%{http_code}" -X POST $API \
            -H "X-SQL-Review-Token: $TOKEN" \
            -H "Content-Type: application/json" \
            -d "$request_body")
          echo "::debug::response $response"

          http_code=$(tail -n1 <<< "$response")
          body=$(sed '$ d' <<< "$response")

          if [ $http_code != 200 ]; then
            echo ":error::Failed to check SQL with response code $http_code and body $body"
            exit 1
          fi

          status=$(echo $body | jq -r '.status')
          content=$(echo $body | jq -r '.content')

          while read message; do
            echo $message
          done <<< "$(echo $content | jq -r '.[]')"

          if [ "$status" == "ERROR" ]; then exit 1; fi
